# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category_choices', models.CharField(choices=[('1', 'Vegetation'), ('2', 'Trees'), ('3', 'Nature'), ('4', 'Abstract'), ('5', 'IT & Computers'), ('6', 'Animals'), ('7', 'Illustrations'), ('8', 'Arts'), ('9', 'Business'), ('10', 'Industries'), ('11', 'Objects'), ('12', 'Technology'), ('13', 'People'), ('14', 'Travel')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=20)),
                ('photo_description', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Order')),
            ],
            options={
                'ordering': ['photo_name'],
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Places'),
        ),
    ]
