# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20180226_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='places',
            new_name='place',
        ),
    ]
