# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20180226_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank='True', height_field='height_field', null='True', upload_to='photos/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='photo',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
