# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20180226_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
