# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_remove_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category_choices',
            field=models.CharField(choices=[('11', 'Vegetation'), ('12', 'Trees'), ('13', 'Nature'), ('14', 'Abstract'), ('15', 'IT & Computers'), ('16', 'Animals'), ('17', 'Illustrations'), ('18', 'Arts'), ('19', 'Business'), ('20', 'Industries'), ('21', 'Objects'), ('22', 'Technology'), ('23', 'People'), ('24', 'Travel')], max_length=10),
        ),
    ]
