# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='order', max_length=30),
        ),
    ]
