# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20180226_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
