# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_auto_20180226_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=20)),
                ('image_description', models.CharField(max_length=30)),
                ('image', models.ImageField(blank='True', height_field='height_field', null='True', upload_to='photos/', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Place',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='place',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Category'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Location'),
        ),
    ]
